### ISSUE TITLE
Syncing the student views.

### ISSUE THREAD

**Issue by nvladimiroff** [nvladimiroff/CSUSeniorProject#9]
So right now the student frontend just loads questions from the server and displays them all in row, but won't sync multiple students at all. Ideally we want to actually sync everyone together. 

This probably isn't too hard to do, but I would need information from the professor view. Some kind of JSON object that has:
- A boolean telling us if the id is even active right now.
- The current question an id is on.
- The time the question started.

Then in the student view, I could just ajax request this, and then syncing everything up should be easy. I know you're still working on the professor view, Glen, so I didn't want to mess with things too much there myself.

**Comment by devglen** [comment]
Yes, I thought of this, in One of the tables (one of the log tables I think, I have to look at it to tell you exactly which one) there is a flag to delineate between an active question or non active question and as I parse through the questions I update that flag so you can send an Ajax request every second or so to see if the value has changed. 

Also when you from the student view answers a question are you updating the answer log table? I'll be reading from that table to display statistics on the answers on the professor page. 

Thanks,

Glen

**Comment by nvladimiroff** [comment]
Right now I'm not updating any tables, just sending a POST request to /api/teacher/:id (that doesn't actually do anything yet) with the selected answer, but I can add that in.

**Comment by devglen** [comment]
I'll be committing my changes probably tonight or tomorrow, I have been holding off because I wanted to just finish it because there was only a few items left and merging sucks! Lol but I'll commit what I have tonight.

**Comment by nvladimiroff** [comment]
Sounds good!

**Comment by devglen** [comment]
Can we do Monday at 6pm 5/2 for the final presentation?

**Comment by nvladimiroff** [comment]
Works for me. Also did you see our grade, Glen? He took a bunch of points
off for no documentation, so we're gonna have to start writing that.

**Comment by devglen** [comment]
Ugh yea I saw damn him. I'll the analysis document this weekend, what exactly does he want from the "programmer guide" ?? I don't know what that means. Connor can do the user guide as it is just taking screen shots and giving instructions on how to use it. I think we can have this done by next week since I'm almost done with the coding part to advance questions from the professor view.

**Comment by nvladimiroff** [comment]
I think all he wants is a rundown of how the code works and stuff. I might
need to ask you stuff about the professor view, but I should at least be
able to get a good start on it over the weekend. Also as soon as you commit
the professor stuff, I'll be able to get syncing working and we'll be
mostly done.

**Comment by devglen** [comment]
I'll try to finish that part tonight then and get it committed since its the last part to make the whole app complete. I'll email you as soon as i do so you know it's out there. Just let me know if you have questions about anything

**Comment by devglen** [comment]
I just committed my new changes. The last thing i have to implement is the completion of a session other than that everything else works. 

Let me know if you need anything, in the meantime I am going to complete the analysis doc and that last coding part. 

Thanks, 

Glen

**Comment by nvladimiroff** [comment]
So I took a look at your code, and it looks pretty good, but what do we want to do about going to the next question? Right now, the student view is on a timer; it cycles to the next question every 15 seconds, but your code just has the professor press a button for the next question. 

Something is gonna have to be rewritten. Which do we want to go with?

**Comment by devglen** [comment]
Well, the database is already set up for the student view to be controlled by the professor clicking next. If you check my code you will see when you click next here it will update the “session_log” table for this session id to mark the “current_question_id” column with the current question Id, so what you could do is just read that value, and query the answers table for that question ID and you will get back all of the answers for that question and display them. 

I think that makes more sense logically than a timer, because if the professor is explaining the question and it takes longer than 15 seconds then you won’t be synced across all viewers. Also depending on when people join the session they will all be out f sync.

**Comment by nvladimiroff** [comment]
I picked 15 just so I'd have some number, it didn't have to be only 15. And for the syncing stuff, that's why I wanted a start time I could query, it would be pretty easy to sync everyone up as long as I had that. 

But if the database is already set up like this, then it'll probably be less work to change my code than yours. So I'll do that, it'll just take me a bit longer to finish than I thought at first.

**Comment by devglen** [comment]
Actually, I misspoke, you want to query the sessions table not session_log. But it would be very easy, much easier than trying to synch each user that hits the page based on a start time. 

It would be one query and one ajax call. 

assuming you have the session ID (which I think you do) 

this is assuming your session ID is 1 or if you want to use the token that I generate and display on the professor page instead of the ID just change ID to token and pass the token value. 
query: select \* from answers where question_id = (select current_question_id from sessions where id = 1) 

then in your route you would use 
app.get(‘/answer/getanswers', function(request, response) {
        sequelize.query(
            'select \* from answers where question_id = (select current_question_id from sessions where id = 1)'
        ).then(function(data){
            response.json(data);
        });
    });

then just make the ajax call to that route and boom you have all your answers. :)

**Comment by nvladimiroff** [comment]
Right now my code already handles the questions, answers and current question by itself (through querying /questions/question_set) because we didn't have sessions before. I think if this was a real project, I'd gut my code and go with that, but right now it'll just be easier to throw in a setInterval that queries /sessions/questionset and updates the current question.

**Comment by devglen** [comment]
When we demonstrate this though I don’t want him to take off points because it doesn’t work correctly. He has been a real d bag lately about this kind of stuff. I’m sure that will be one of the questions because that is a key feature for the “clicker” app is it being in synch with what the professor is displaying. Why can’t your code query sessions table? I only ask because I am writing this analysis and design document and I put functional requirements in it one being that the professor view and student view will be synced. 

Also another feature I added was reporting for each question as they are being answered, I am querying the answer_log table, so when you answer a question are you logging the answer ID in that table? When I query that table I need the answer Id and session Id (all existing columns).

**Comment by nvladimiroff** [comment]
Everything will be synced, don't worry. I'm having setInterval query /sessions/question_set every second, and if there's a change, I just update everything to the new question. /sessions/question_set still queries the session table. What I meant was that some chunks of my code could be simplified now that we have a sessions route, but that would take some time that we probably don't have.

It's not adding anything to the table yet, but it will be soon. The client side is all setup for it, I just need another post block and a bit of sequelize in the server code.

**Comment by devglen** [comment]
We may need to test this before we demonstrate it. I don’t update the question_set table at all during a session. the only updating I do is to the sessions table. So if you are looking for an update there I don’t think it will ever change, from question to question.

**Comment by nvladimiroff** [comment]
No, I mean the [/sessions/questionset route in sessions.js](https://github.com/nvladimiroff/CSUSeniorProject/blob/master/routes/sessions.js#L27). It doesn't query the question_set table, it queries the sessions table. It gives a chunk of JSON like this:
`{"id":2,"token":"c82703b0-0a6a-11e6-89d9-996e2993c1a6","question_set_id":2,"current_question_id":5,"owner_id":"nickv","created":"2016-04-24T22:20:42.000Z","modified":"2016-04-24T22:24:55.000Z","status":true,"is_active":true}`

**Comment by devglen** [comment]
Ahh I see, so how do you get the answers for the question? It seems like a very round about way of doing it as opposed to the one query but I guess its ok as long as it works. We probably should test it though so there aren’t any surprises when we demonstrate it to him. 
I just can’t fail this stupid class because I’m graduating and the last time I took a class by Blake everything seemed fine until the last project and I failed because of something stupid. He’s doing the same thing in 368, he gave everyone perfect scores for all the assignments but our final grade is going to be based on the final project, and if we don’t do that correctly he is for sure going to fail them.

**Comment by devglen** [comment]
I also don’t want a C lol I want an A because that what I think we deserve and I need to get a 3.5 or higher this semester and this class I counted as an A.

**Comment by nvladimiroff** [comment]
I get the answers from [/questions/question_set/](https://github.com/nvladimiroff/CSUSeniorProject/blob/master/routes/questions.js#L12). And yeah, like I said this is a bit roundabout because I wrote all this code **before** we had sessions, so this was the only way to do it then. We just have too much to do to bother rewriting something that already works.

As long as we have all our documentation and our shit works, I'm sure we'll get an A. Also, I've been hearing pretty much everyone complain about 368. Kyle especially was pretty pissed.

**Comment by nvladimiroff** [comment]
Ok, syncing works and is committed now. I'll get the answers in the database probably on Wednesday. Once you finish finishing sessions, I should be able to throw that in really quick as well.
